### ISSUE TITLE
Led holes

### ISSUE THREAD

**Issue by BenRoe** [daprice/keyswitches.pretty#1]
Hello,
thank you for sharing the footprints. Is it possible to add LED holes?

**Comment by daprice** [comment]
I mainly created this library because I needed reversible/socketable footprints where there isn’t room for LEDs, so I’ve simply left it up to board designers using the simpler footprints to handle LED connections if they want them (along with deciding what type they need: thru hole, SMT, or recessed, along with pin count, what pitch, etc that could vary from one board to another).

For now, that means having the LED as a separate component on the PCB in KiCad and positioning its footprint wherever it needs to be under the switch footprint (I’m not aware of a nice way to do this for all the switches on a board in the KiCad GUI, but theoretically it could be scripted if you don’t like aligning a lot of footprints manually).

That said, I’m open to the idea of having LED pads be part of the switch footprint if someone wants to add them and submit a pull request.

**Comment by BenRoe** [comment]
Thanks for the detailed answer. You are right. Separate LED foodprint is simpler.
